//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mascota
    {
        public int id_mascota { get; set; }
        public string nom_mascota { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string peso { get; set; }
        public string edad { get; set; }
        public string color { get; set; }
        public string raza { get; set; }
        public Nullable<int> id_vet { get; set; }
        public byte[] foto { get; set; }
    
        public virtual veterinario veterinario { get; set; }
    }
}
