//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicios
    {
        public int idServicios { get; set; }
        public string nombreServicio { get; set; }
        public string caracteristicas { get; set; }
        public Nullable<decimal> precio { get; set; }
    }
}
