//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class veterinario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public veterinario()
        {
            this.mascota = new HashSet<mascota>();
        }
    
        public int id_vet { get; set; }
        public string nom_vet { get; set; }
        public string ape_vet { get; set; }
        public string dirección { get; set; }
        public string telefono { get; set; }
        public string especialidad { get; set; }
        public string foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mascota> mascota { get; set; }
    }
}
